const CHANGE_SEARCH_FIELD_ACTION = 'CHANGE_SEARCH_FIELD'

const REQUEST_ROBOTS_STATE_PENDING = 'REQUEST_ROBOTS_STATE_PENDING'
const REQUEST_ROBOTS_STATE_SUCCESS = 'REQUEST_ROBOTS_STATE_SUCCESS'
const REQUEST_ROBOTS_STATE_FAILED = 'REQUEST_ROBOTS_STATE_FAILED'

const JSON_PLACEHOLDER_URL = 'https://jsonplaceholder.typicode.com/users'

const Constants = {
  CHANGE_SEARCH_FIELD_ACTION,
  REQUEST_ROBOTS_STATE_PENDING,
  REQUEST_ROBOTS_STATE_SUCCESS,
  REQUEST_ROBOTS_STATE_FAILED,
  JSON_PLACEHOLDER_URL
}

export default Constants
